version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bitbucket-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filestorage_db

  backend:
    build: ./backend
    container_name: bitbucket-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
